# Autogenerated wrapper script for AppBundlerUtils_jll for aarch64-apple-darwin
export macos_launcher

JLLWrappers.@generate_wrapper_header("AppBundlerUtils")
JLLWrappers.@declare_executable_product(macos_launcher)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        macos_launcher,
        "bin/macos_launcher",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
